config/routes.rb
Rails.application.routes.draw do
  get 'year/new'
  get 'year/edit'
  get 'templates/new'
  get 'templates/edit'
  get 'templatetypes/new'
  get 'templatetypes/create'
  get 'templatetypes/index'
  get 'templatetypes/edit'
  get 'templatetypes/update'
  get 'templatetypes/destory'
  get 'users/new'
  devise_for :users
  resources :sheets, only: [:update] do
    collection do
      put :sign_in_student, path: "sign_in_student/:id/:date"
      put :unsign_in_student, path: "unsign_in_student/:id/:date"
      delete :destroy_sheet, path: "destroy_sheet/:id/:date"
      post :create_sheet, path: "create_sheet/:id/:template_id/:date"
    end
  end
  resources :usertypes, except: [:show]
  resources :grades, except: [:show]
  resources :users, except: [:show] do
    collection do
      put :update_multiple
      get :archived, path: ":id/archived"
      post :import
      get :edit_multiple, path: "edit-multiple"
      get :search, path: "search-users"
      get :progress_grades, path: "progress-grades"
      get :bulk_delete_students, path: "bulk-delete-students"
    end
  end
  resources :templatetypes, except: [:show, :index]
  resources :templates do
    collection do
      post :add_schedule_date, path: "add_schedule_date/:id/:date"
      delete :delete_schedule_date, path: "delete_schedule_date/:id/:date"
    end
  end

  resources :years, except: [:show, :index]
  root to: 'users#index_student'
  get 'users/supervisors', to: 'users#index_supervisor'
  get 'users/:id', to: 'users#show'
  #root to: 'dashboards#admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/templates/_form.html.erb
<%= form_for @template do |f| %>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.label :year_id %>
        <%= collection_select(:template, :year_id, Year.all, :id, :year, {include_blank: true}, { class: "form-control" }) %>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= f.label :templatetype_id %>
        <%= collection_select(:template, :templatetype_id, Templatetype.all, :id, :template_type, {include_blank: true}, { class: "form-control" }) %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit(@template.new_record? ? "Create" : "Update", class:'btn btn-primary')%>
  </div>

<% end %>

app/views/templates/edit.html.erb
<div class="jumbotron">
  <h1 class="text-center">Edit a Template</h1>
</div>
<%= render 'templates/form' %>

app/views/templates/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Building Templates</h1>
</div>

<div class="row">
  <div class="col-sm">
    <div class="text-center">
        <h1>Template Types <%= link_to "Add", new_templatetype_path, class: "btn btn-primary" %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Template Type</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @templatetypes.each do |templatetype| %>
          <tr>
            <th scope="row"><%= templatetype.id %></th>
            <td><%= link_to templatetype.template_type, edit_templatetype_path(templatetype)  %></td>
            <td><%= link_to "Delete", templatetype_path(templatetype), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm">
    <div class="text-center">
        <h1>Year <%= link_to "Add", new_year_path, class: "btn btn-primary" %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Year</th>
          <th scope="col">Active</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @years.each do |year| %>
          <tr>
            <th scope="row"><%= year.id %></th>
            <td><%= link_to year.year, edit_year_path(year)  %></td>
            <td><%= year.current_year  %></td>
            <td><%= link_to "Delete", year_path(year), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-sm">
    <div class="text-center">
        <h1>Active Templates <%= link_to "Add", new_template_path, class: "btn btn-primary" %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Template</th>
          <th scope="col" class="text-center">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @templates.each do |template| %>
          <tr>
            <th scope="row"><%= template.id %></th>
            <td><%= link_to template.template_name, edit_template_path(template)  %></td>
            <td><%= link_to "Build Calendar", template_path(template), class: "btn btn-sm btn-primary" %></td>
            <td><%= link_to "Delete", template_path(template), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/templates/new.html.erb
<div class="jumbotron">
  <h1 class="text-center">Create a Template</h1>
</div>
<%= render 'templates/form' %>

app/views/templates/show.html.erb
<div class="jumbotron">
  <h1 class="text-center"><%= @template.template_name %></h1>
  <hr class="my-4">
  <%= link_to "Edit Template", edit_template_path(@template), class: "btn btn-primary" %>
  <%= link_to "Delete", '#', class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

<%= month_calendar do |date| %>
  <%= date.day %>
  <% if @schedule_dates.include?(date) %>
    <div class="text-center">
      <%= link_to "Delete",  delete_schedule_date_templates_path(params[:id], date: date), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'You are about to delete a template date.  If any student that has this template has signed in on this date, that sign in record will be delete. This process cannot be undone. Are you sure you want to do that?'} %>
    </div>
  <% else %>
    <div class="text-center">
      <%= link_to "Add", add_schedule_date_templates_path(params[:id], date: date), class: "btn btn-sm btn-success", method: :post %>
    </div>
  <% end %>
<% end %>

app/views/templates/working-templates.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <th scope="row"><%= schedule.id %></th>
        <td><%= schedule.date  %></td>
        <td><%= link_to "Delete", '#', class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= month_calendar event: @schedules do |date, schedules| %>
  <%= date.day %>
  <% @schedules.each do |schedule| %>
    <% if schedule.date == date %>
      <%= link_to "Delete", '#', class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>

    <% end %>
  <% end %>
<% end %>

<%= month_calendar event: @schedules do |date, schedules| %>
  <%= date.day %>
  <% @schedules.each do |schedule| %>
    <% if schedule.date != date %>
      <div class="text-center">
        <%= link_to "Add", '#', class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
    <% if schedule.date == date %>
      <div class="text-center">
        <%= link_to "Delete", '#', class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  <% end %>
<% end %>

<%= month_calendar do |date| %>
  <%= date.day %>
  <% if @schedules.include?(date) %>
    <div class="text-center">
      <%= link_to "Add", '#', class: "btn btn-sm btn-success", method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
  <% end %>
<% end %>