config/routes.rb
Rails.application.routes.draw do
  get 'year/new'
  get 'year/edit'
  get 'templates/new'
  get 'templates/edit'
  get 'templatetypes/new'
  get 'templatetypes/create'
  get 'templatetypes/index'
  get 'templatetypes/edit'
  get 'templatetypes/update'
  get 'templatetypes/destory'
  get 'users/new'
  devise_for :users
  resources :sheets, only: [:update] do
    collection do
      put :sign_in_student, path: "sign_in_student/:id/:date"
      put :unsign_in_student, path: "unsign_in_student/:id/:date"
      delete :destroy_sheet, path: "destroy_sheet/:id/:date"
      post :create_sheet, path: "create_sheet/:id/:template_id/:date"
    end
  end
  resources :usertypes, except: [:show]
  resources :grades, except: [:show]
  resources :users, except: [:show] do
    collection do
      put :update_multiple
      get :archived, path: ":id/archived"
      post :import
      get :edit_multiple, path: "edit-multiple"
      get :search, path: "search-users"
      get :progress_grades, path: "progress-grades"
      get :bulk_delete_students, path: "bulk-delete-students"
    end
  end
  resources :templatetypes, except: [:show, :index]
  resources :templates do
    collection do
      post :add_schedule_date, path: "add_schedule_date/:id/:date"
      delete :delete_schedule_date, path: "delete_schedule_date/:id/:date"
    end
  end

  resources :years, except: [:show, :index]
  root to: 'users#index_student'
  get 'users/supervisors', to: 'users#index_supervisor'
  get 'users/:id', to: 'users#show'
  #root to: 'dashboards#admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
after_update :create_schedules_in_sheets

  devise :database_authenticatable,
         :recoverable, :rememberable
  belongs_to :grade, optional: true
  belongs_to :usertype, optional: true

  has_many :students, class_name: "User",
                          foreign_key: "supervisor_id"

  belongs_to :supervisor, class_name: "User", optional: true

  belongs_to :template, optional: true
  has_many :sheets

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name }"
  end


  def self.first_name_search(param)
    search_for('first_name', param)
  end

  def self.last_name_search(param)
    search_for('last_name', param)
  end

  def self.search_for(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end
  #
  def self.full_search(search)
    find_by_sql "SELECT u.id, u.first_name || ' ' || u.last_name as fullname FROM users u WHERE fullname LIKE '%#{search}%'"
  end

  def self.full_name_search(search)
    param.strip!
    to_send_back = User.select("first_name || ' ' || last_name as FullName").where("FullName LIKE ?", "%#{param}%")
    return nil unless to_send_back
    to_send_back
  end

  def self.to_csv(fields = column_names, options = {})

    CSV.generate(options) do |csv|
      csv << fields
      all.each do |user|
        csv << user.attributes.values_at(*fields)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user_hash = row.to_hash
      user = find_or_create_by!(email: user_hash['email'], first_name: user_hash['first_name'], last_name: user_hash['last_name'], :encrypted_password => user_hash['password'], usertype_id: 1, grade_id: 1)
      user.update_attributes(user_hash)
    end
  end


  def count_missing_dates
    @template = Template.joins(:year).merge(Year.where(:current_year => true))
    active_sheets = Sheet.where(template_id: @template)
    @sheets = active_sheets.where(user_id: self.id)
    @sheet_dates = @sheets.distinct.pluck(:date)
    sign_ins = @sheets.where("date <= ?", Date.yesterday())
    @total_missed = sign_ins.where(signed_in: false).count
    return @total_missed
  end

  def count_students
    User.where(supervisor_id: self.id).count
  end


  def create_schedules_in_sheets
    @schedules = Schedule.where(template_id: self.template_id)
    @sheets = Sheet.where(user_id: self.id)
    @sheet_dates = @sheets.distinct.pluck(:date)
    @schedule_dates = @schedules.distinct.pluck(:date)
    if @sheets.count > 0
      @sheets.each do |sheet|
        if (@schedule_dates.exclude?(sheet.date) && sheet.template.year.current_year == true)
          @sheets.where(date: sheet.date).delete_all
        end
      end
    end
    @schedules.each do |schedule|
      if @sheet_dates.include?(schedule.date)
        sheet = @sheets.where(date: schedule.date)
        sheet.update(template_id: self.template_id)
      else
        Sheet.create(user_id: self.id, template_id: schedule.template_id, date: schedule.date, signed_in: false)
      end
    end
  end

private

def set_active_templates
  @template = Template.joins(:year).merge(Year.where(:current_year => true))
end


end

app/models/usertype.rb
class Usertype < ApplicationRecord
  has_many :users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:edit, :update, :show, :destroy, :archived, :require_same_user]
before_action :set_active_templates, only: [:new, :edit, :show, :edit_multiple]
before_action :require_admin, except: [:index_student, :show]
before_action :require_same_user, only: [:show]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.first_name = @user.first_name.titlecase
    @user.last_name = @user.last_name.titlecase
    if @user.save
      if @user.template_id != nil
        create_schedules_in_sheets(@user.id, @user.template_id)
      end
      flash[:notice] = "User was successfully created"
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages.first
      redirect_to new_user_path
    end
  end

  def edit

  end

  def advance_grades
    ninth_graders = User.find_by_sql"Update * FROM users INNER JOIN grades ON grades.id = users.grade_id WHERE grades.grade_level = 9"
    ninth_graders.update()
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update(user_params)
      #@templates = Template.joins(:year).merge(Year.where(:current_year => true))
      #@active_templates = @templates.distinct.pluck(:id)

      #if @active_templates.include?(@user.template_id)
      if @user.template_id != nil
        create_schedules_in_sheets(@user.id, @user.template_id)
      end
      flash[:notice] = "User was successfully updated"
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages.first
      redirect_to root_path
    end
  end

  def create_schedules_in_sheets(user, sche)
    @schedules = Schedule.where(template_id: sche)
    @sheets = Sheet.where(user_id: user)
    @sheet_dates = @sheets.distinct.pluck(:date)
    @schedule_dates = @schedules.distinct.pluck(:date)
    if @sheets.count > 0
      @sheets.each do |sheet|
        if (@schedule_dates.exclude?(sheet.date) && sheet.template.year.current_year == true)
          @sheets.where(date: sheet.date).delete_all
        end
      end
    end
    @schedules.each do |schedule|
      if @sheet_dates.include?(schedule.date)
        sheet = @sheets.where(date: schedule.date)
        sheet.update(template_id: sche)
      else
        Sheet.create(user_id: user, template_id: schedule.template_id, date: schedule.date, signed_in: false)
      end
    end
  end

  def index_student
    if !logged_in_user_admin?
      redirect_to user_path(current_user)
    end


    @students = User.joins(:usertype).merge(Usertype.where(:user_type => 'student'))

    respond_to do |format|
      format.html
      format.csv { send_data @students.to_csv(['email', 'first_name', 'last_name']) }
    end
  end

  def index_supervisor
    @supervisors = User.joins(:usertype).merge(Usertype.where.not(:user_type => 'student'))
  end

  def show
    if !user_is_student?
      find_active_sheets_for_multiple_students
    end

    if user_is_student?
      find_active_sheets
    end
  end

  def find_active_sheets_for_multiple_students
    @students = User.where(supervisor_id: params[:id])
  end

  def find_active_sheets
    active_sheets = Sheet.where(template_id: @templates)
    @sheets = active_sheets.where(user_id: params[:id])
    @sheet_dates = @sheets.distinct.pluck(:date)
    sign_ins = @sheets.where("date <= ?", Date.yesterday())
    @total_sign_ins = sign_ins.count
    @total_worked = sign_ins.where(signed_in: true).count
    @total_missed = sign_ins.where(signed_in: false).count
  end

  def search
    user = params[:user]
    @searched_user = User.full_search(user)
    if @searched_user.count == 1
      redirect_to user_path(@searched_user.first)
    elsif @searched_user.count > 1
      flash[:notice] = "There was more that one search result. If this isn't the right person, do a more detailed search."
      redirect_to user_path(@searched_user.first)
    else
      flash[:alert] = "No one matched that search result."
      redirect_to root_path
    end
  end

  def edit_multiple
    @students = User.where(usertype_id: 1)
  end

  def update_multiple
    User.update(params[:students].keys, params[:students].values)
    # need to figure how to run this action for template_ids that have been updated: create_schedules_in_sheets(student.id, student.template_id)
    flash[:notice] = "Students has been updated."
    redirect_to root_path
  end

  def destroy
    if user_is_student?
      Sheet.where(user_id: @user).delete_all
    end
    if user_is_supervisor?
      User.where(supervisor_id: @user).update(supervisor_id: nil)
    end
    @user.destroy
    flash[:notice] = "#{@user.full_name} has been deleted."
    redirect_to root_path
  end

  def import
    User.import(params[:file])
    flash[:notice] = "Users have been imported."
    redirect_to root_path
  end

  def archived
    @sheets = Sheet.where(user_id: params[:id]).order(:date)
  end

  def progress_grades
    grades = Grade.all.order(grade_level: :desc)
    grades.each do |grade|
    	current_grade = grade.id
    	next_grade = grade.next_grade_id
    	User.where(grade_id: current_grade).update(grade_id: next_grade)
    end
    flash[:notice] = "All student grades have been advanced to their next grade"
    redirect_to root_path
  end

  def bulk_delete_students
    grade = Grade.where(next_grade_id: nil)
    users_to_delete = User.where(grade_id: grade)
    Sheet.where(user_id: users_to_delete).delete_all
    users_to_delete.destroy_all
    flash[:notice] = "All students with a next grade set to 'blank' has been deleted"
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :usertype_id, :supervisor_id, :grade_id, :password, :password_confirmation, :template_id)
  end

  def sheet_params
    params.require(:sheet).permit(:date, :signed_in)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_active_templates
    @templates = Template.joins(:year).merge(Year.where(:current_year => true))
  end

  def require_same_user
    # students = User.where(supervisor_id: params[:id])
    # student_ids = students.distinct.pluck(:id)
    if logged_in_user_student? && current_user.id != @user.id
      flash[:alert] = "You don't have access to other's page."
      redirect_to root_path
    end
    # if (logged_in_user_supervisor? && current_user.id != @user.id) || (logged_in_user_supervisor? && student_ids.include?(@user.id))
    #   flash[:alert] = "You don't have access that page."
    #   redirect_to root_path
    # end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_student_header.html.erb
<div class="jumbotron">
  <h1 class="text-center"><%= @user.full_name.titlecase %></h1>
  <h4 class="text-center"><%= @user.usertype.user_type %> </h4>
  <% if user_is_student? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="text-center">Days</th>
          <th scope="col" class="text-center">Worked</th>
          <th scope="col" class="text-center">Missed</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="text-center"><%= @total_sign_ins %></th>
          <td class="text-center"><%= @total_worked %></td>
          <td class="text-center"><%= @total_missed %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <% if logged_in_user_admin? %>
    <hr class="my-4">
      <% if user_is_student? %>
        <%= link_to "View Current Year ", user_path(@user), class: "btn btn-primary" %>
        <%= link_to "Archived Calendars", archived_users_path(@user), class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Edit User", edit_user_path(@user), class: "btn btn-primary" %>
      <%= link_to "Delete User", user_path(@user), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>

app/views/users/_students_partial.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Grade</th>
      <% if current_page?(root_path) %>
        <th scope="col">Supervisor</th>
      <% else %>
        <th scope="col">Email</th>
      <% end %>
      <th scope="col">Missed Days</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <th scope="row"><%= student.id %></th>
        <td><%= link_to student.full_name, user_path(student), method: :get %></td>
        <td><%= student.grade.grade_level %></td>
        <% if current_page?(root_path) %>
          <td><%= student.supervisor.full_name %></td>
        <% else %>
          <td><%= student.email %></td>
        <% end %>
        <td><%= student.count_missing_dates %></td>
        <td><%#= link_to "Delete", user_path(user.id), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/archived.html.erb
<%= render 'users/student_header' %>

<% if @sheets.count > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Date</th>
        <th scope="col">Template</th>
        <th scope="col">Signed In?</th>
      </tr>
    </thead>
    <tbody>
      <% @sheets.each do |sheet| %>
        <tr>
          <th scope="row"><%= sheet.id %></th>
          <td><%= sheet.date %></td>
          <td><%= sheet.template.template_name %></td>
          <% if sheet.signed_in == nil || sheet.signed_in == false%>
            <td class="archived">
              <%= fa_icon 'times-circle 2x' %>
            </td>
          <% else %>
            <td>
              <%= fa_icon 'check 2x' %>
            </td>
          <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/edit.html.erb
<%= render 'users/student_header' %>

<%= form_for(@user, url: user_path(@user), html: { method: :put }) do |f| %>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, autocomplete: "first_name", class: "form-control" %>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, autocomplete: "last_name", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control col-6" %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <label>New Password</label>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <label>New Password Confirmation</label>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
      </div>
    </div>
  </div>



  <div id="student-options">

    <div class="form-group">
      <%= f.label "Grade" %>
      <%= collection_select(:user, :grade_id, Grade.all, :id, :grade_level, {include_blank: true}, { class: "form-control col-6" }) %>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <%= f.label "Supervisor" %>
          <%= collection_select(:user, :supervisor_id, User.where.not(usertype_id: 1), :id, :full_name, {include_blank: true}, { class: "form-control" })  %>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group">
          <%= f.label "Template" %>
          <%= collection_select(:user, :template_id, @templates, :id, :template_name, {include_blank: true}, { class: "form-control" }) %>
        </div>
      </div>
    </div>

  <div class="actions">
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit_multiple.html.erb
<div class="jumbotron">
  <h1 class="text-center">Students</h1>
  <hr class="my-4">
  <%= link_to "Add New Student", new_user_path, class: "btn btn-primary" %>
  <%= link_to "Grid Edit", edit_multiple_users_path, class: "btn btn-primary" %>
</div>
<%= form_tag update_multiple_users_path, method: :put do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Grade</th>
        <th scope="col">Supervisor</th>
        <th scope="col">Template</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <%= fields_for "students[]", student do |f| %>
          <tr>
            <td><%= link_to student.full_name, user_path(student) %></td>
            <td><%= student.grade.grade_level unless student.grade_id == nil %></td>
            <td><%= f.collection_select(:supervisor_id, User.where(usertype_id: 2), :id, :full_name, {include_blank: true}, { class: "form-control" })  %></td>
            <td><%= f.collection_select(:template_id, @templates, :id, :template_name, {include_blank: true}, { class: "form-control" }) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="form-group">
    <%= submit_tag "Update", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/index_student.html.erb
<div class="jumbotron">
  <h1 class="text-center">Students</h1>
  <hr class="my-4">
  <%= link_to "Add New Student", new_user_path, class: "btn btn-primary" %>
  <%= link_to "Grid Edit", edit_multiple_users_path, class: "btn btn-primary" %>
  <%= link_to "Advance Grades", progress_grades_users_path, class: "btn btn-primary" %>
  <%= link_to "Bulk Delete",   bulk_delete_students_users_path, class: "btn btn-danger" %>
  <h3>Import Users</h3>
  <%= form_tag import_users_path, multipart: true, class: 'form-inline' do %>
    <div class="form-group">
      <%= link_to "Export Students", root_path(format: :csv), class: "btn btn-primary" %>
    </div>
    <div class="form-group">
      <%= file_field_tag :file %>
    </div>
    <div class="form-group">
      <%= submit_tag "Upload Students", class: "btn btn-info" %>
    </div>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Grade</th>
      <th scope="col">Email</th>
      <th scope="col">Supervisor</th>
      <th scope="col">Template Type</th>
      <th scope="col" class="text-center">Missed</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <th scope="row"><%= student.id %></th>
        <td><%= link_to student.full_name, user_path(student) %></td>
        <td><%= student.grade.grade_level unless student.grade == nil %></td>
        <td><%= link_to student.email, "mailto:#{student.email}" %></td>
        <td><%= link_to student.supervisor.full_name, user_path(student.supervisor.id) unless student.supervisor == nil %></td>
        <td><%= link_to student.template.template_name, template_path(student.template.id) unless student.template == nil %> </td>
        <td class="text-center"><%= student.count_missing_dates %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index_supervisor.html.erb
<div class="jumbotron">
  <h1 class="text-center">Supervisors</h1>
  <hr class="my-4">
  <%= link_to "Add New Supervisor", new_user_path, class: "btn btn-primary" %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Type</th>
      <th scope="col" class="text-center">Number of Students</th>
    </tr>
  </thead>
  <tbody>
    <% @supervisors.each do |supervisor| %>
      <tr>
        <th scope="row"><%= supervisor.id %></th>
        <td><%= link_to supervisor.full_name, user_path(supervisor) %></td>
        <td><%= link_to supervisor.email, "mailto:#{supervisor.email}" %></td>
        <td><%= supervisor.usertype.user_type %>
        <td class="text-center"><%= supervisor.count_students %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="jumbotron">
  <h1 class="text-center">Create New User</h1>
</div>

<%= form_for @user do |f| %>

<div class="row">
  <div class="col-6">
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, autocomplete: "first_name", class: "form-control" %>
    </div>
  </div>
  <div class="col-6">
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, autocomplete: "last_name", class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control col-6" %>
</div>

<div class="row">
  <div class="col-6">
    <div class="form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>
  </div>

  <div class="col-6">
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label "User Type" %><br />
  <%= collection_select(:user, :usertype_id, Usertype.all, :id, :user_type,  {include_blank: true}, { class: "form-control col-6" }) %>
</div>

<div id="student-options">

  <div class="form-group">
    <%= f.label "Grade" %>
    <%= collection_select(:user, :grade_id, Grade.all, :id, :grade_level, {include_blank: true}, { class: "form-control col-6" }) %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.label "Supervisor" %>
        <%= collection_select(:user, :supervisor_id, User.where(usertype_id: 2), :id, :full_name, {include_blank: true}, { class: "form-control" })  %>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= f.label "Template" %>
        <%= collection_select(:user, :template_id, @templates, :id, :template_name, {include_blank: true}, { class: "form-control" }) %>
      </div>
    </div>
  </div>
</div>

<div class="actions">
  <%= f.submit "Create", class: "btn btn-success" %>
</div>
<% end %>

app/views/users/non_active_years.html.erb
<div class="jumbotron">
  <h1 class="text-center"><%= @user.full_name %></h1>
  <h4 class="text-center"><%= @user.usertype.user_type %> </h4>
  <hr class="my-4">
  <%= link_to "Edit User", edit_user_path(@user), class: "btn btn-primary" %>
</div>

<% if @sheets.count > 0 %>
  <%= month_calendar do |date| %>
    <%= date.day %>
    <% @sheets.each do |sheet| %>
      <% if sheet.date == date %>
        <% if sheet.signed_in == true %>
          <div class="text-center">
            <%= link_to "Done", unsign_in_student_sheets_path(@user.id, date: date), class: "btn btn-success btn-sm", method: :put, data: {confirm: 'You are about to unsign in. Are you sure you want to do that?'} %>
          </div>
        <% else %>
          <div class="text-center">
            <%= link_to "Sign In",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-danger btn-sm", method: :put %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'users/student_header' %>


<% if !user_is_student? %>
  <%= render 'users/students_partial' %>
<% end %>

<% if user_is_student? %>
  <%= month_calendar do |date| %>
    <%= date.day %>
    <% @sheets.each do |sheet| %>
      <% if sheet.date == date %>
        <% if sheet.signed_in == true %>
          <%# <% if logged_in_user_admin? %>
            <!--<span class="delete-date">
              <%#= link_to ('<i class="fa fa-times-circle"></i>').html_safe, destroy_sheet_sheets_path(@user.id, date), method: :delete, data: {confirm: 'You are about to delete a date for a student. Are you sure you want to do that?'}%>
            </span>-->
          <%# end %>
          <div class="text-center">
            <% if logged_in_user_admin? || logged_in_user_supervisor? || (logged_in_user_student? && Date.today == date)%>
              <%= link_to "Done", unsign_in_student_sheets_path(@user.id, date: date), class: "btn btn-success btn-sm", method: :put, data: {confirm: 'You are about to unsign in. Are you sure you want to do that?'} %>
            <% else %>
              <%= link_to "Done", unsign_in_student_sheets_path(@user.id, date: date), class: "btn btn-success btn-sm disabled", method: :put, data: {confirm: 'You are about to unsign in. Are you sure you want to do that?'} %>
            <% end %>
          </div>
        <% else %>
          <%# if logged_in_user_admin? %>
            <!--<span class="delete-date">
              <span class="delete-date">
                <%#= link_to ('<i class="fa fa-times-circle"></i>').html_safe, destroy_sheet_sheets_path(@user.id, date), method: :delete, data: {confirm: 'You are about to delete a date for a student. Are you sure you want to do that?'}%>
              </span>
            </span>-->
          <%# end %>
          <div class="text-center">
            <% if logged_in_user_admin? || logged_in_user_supervisor? %>
              <% if Date.today == date %>
                <%= link_to "Sign In",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-warning btn-sm", method: :put %>
              <% elsif Date.today > date %>
                <%= link_to "Missed",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-danger btn-sm", method: :put %>
              <% else %>
                <%= link_to "Scheduled",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-primary btn-sm", method: :put %>
              <% end %>
            <% end %>

            <% if logged_in_user_student? %>
              <% if Date.today == date %>
                <%= link_to "Sign In",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-warning btn-sm", method: :put %>
              <% elsif Date.today > date %>
                <%= link_to "Missed",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-danger btn-sm disabled", method: :put %>
              <% else %>
                <%= link_to "Scheduled",  sign_in_student_sheets_path(@user.id, date: date), class: "btn btn-primary btn-sm disabled", method: :put %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <%# if @sheet_dates.exclude?(date) %>
      <% if logged_in_user_admin? && @user.template_id != nil %>
        <!--<span class="delete-date">
          <%#= link_to ('<i class="fa fa-plus-circle"></i>').html_safe, create_sheet_sheets_path(@user.id, @user.template_id, date), method: :post %>
        </span>-->
      <%# end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/working-show.html.erb
<% if @sheets.count > 0 %>
  <%= form_tag update_multiple_users_path, method: :put do %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Sign In</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @sheets.each do |date| %>
          <%= fields_for "dates[]", date do |f| %>
            <tr>
              <td><%= date.date %></td>
              <td><%= f.check_box :signed_in %></td>
              <td><%= link_to "Delete", '#', class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="form-group">
      <%= hidden_field_tag(:id, @user.id) %>
      <%= submit_tag "Update", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>