config/routes.rb
Rails.application.routes.draw do
  get 'year/new'
  get 'year/edit'
  get 'templates/new'
  get 'templates/edit'
  get 'templatetypes/new'
  get 'templatetypes/create'
  get 'templatetypes/index'
  get 'templatetypes/edit'
  get 'templatetypes/update'
  get 'templatetypes/destory'
  get 'users/new'
  devise_for :users
  resources :sheets, only: [:update] do
    collection do
      put :sign_in_student, path: "sign_in_student/:id/:date"
      put :unsign_in_student, path: "unsign_in_student/:id/:date"
      delete :destroy_sheet, path: "destroy_sheet/:id/:date"
      post :create_sheet, path: "create_sheet/:id/:template_id/:date"
    end
  end
  resources :usertypes, except: [:show]
  resources :grades, except: [:show]
  resources :users, except: [:show] do
    collection do
      put :update_multiple
      get :archived, path: ":id/archived"
      post :import
      get :edit_multiple, path: "edit-multiple"
      get :search, path: "search-users"
      get :progress_grades, path: "progress-grades"
      get :bulk_delete_students, path: "bulk-delete-students"
    end
  end
  resources :templatetypes, except: [:show, :index]
  resources :templates do
    collection do
      post :add_schedule_date, path: "add_schedule_date/:id/:date"
      delete :delete_schedule_date, path: "delete_schedule_date/:id/:date"
    end
  end

  resources :years, except: [:show, :index]
  root to: 'users#index_student'
  get 'users/supervisors', to: 'users#index_supervisor'
  get 'users/:id', to: 'users#show'
  #root to: 'dashboards#admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if !logged_in_user_admin? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", root_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if logged_in_user_admin? %>
          <li class="nav-item">
            <a href="/" class="nav-link <%= 'active' if current_page?(root_path) %>">Students</a>
          </li>
          <li class="nav-item">
            <a href="/users/supervisors" class="nav-link <%= 'active' if current_page?(users_supervisors_path) %>">Supervisors</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= 'active' if current_page?(templates_path) || current_page?(grades_path) || current_page?(usertypes_path)%>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Schedule
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Template Setup", templates_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Student Grades", grades_path, class: "dropdown-item" %>
              <%= link_to "User Types", usertypes_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "btn btn-danger", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
      <% if logged_in_user_admin? %>
        <%= form_tag search_users_path, method: :get, class:"form-inline my-2 my-lg-0"  do %>
          <%= text_field_tag :user, params[:user], placeholder: "Search Users", autofocus: true, class: "form-control mr-sm-2" %>
          <%= button_tag "Search", type: :submit, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timesheet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navigation' %>
    <% end %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div  </body>
</html>